---
site_runtime: NODE_V16
site_routes:
  static_route: "*"
  not_found_route: "/404.html"
  internal_server_error_route: "/500.html"
site_version_deployment_artifacts:
  site_version_artifact: siteVersion.json
  static_dir: dist
  serverless_dir: target
site_version_schema:
  pages:
    - name: Home
      blocks:
        - name: Body
          views:
            - name: Books
              columns:
                - name: Name
                  type: TEXT
                - name: Description
                  type: TEXT
                - name: Image URL
                  type: FILE
                - name: Category
                  type: OPTION
                - name: Published at
                  type: DATE_TIME
